[workspace]

members = [
    "mla",
    "mlakey-parser",
    "mlar",
    "mla-fuzz-afl",
    "bindings/C",
]

[profile.release]
opt-level = 'z'     # Optimize for size.
lto = true          # Enable Link Time Optimization
